-- POSTS 테이블 생성
CREATE TABLE IF NOT EXISTS POSTS (
    NO         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Primary Key, 자동 증가
    TITLE      VARCHAR(200) NOT NULL,                               -- 최대 200자, 필수 입력
    CONTENT    CLOB         NOT NULL,                               -- 10MB까지 입력 가능 (H2 CLOB), 필수 입력
    CREATED_AT TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,     -- 기본값 현재 시각
    UPDATED_AT TIMESTAMP    DEFAULT NULL,                           -- 기본값 NULL
    VIEWS      INT          DEFAULT 0 NOT NULL                      -- 기본값 0
);
